package com.imark.system.model;

// Generated 2015-12-3 14:38:08 by Hibernate Tools 3.2.2.GA

import java.sql.Clob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * Article generated by hbm2java
 */
@Entity
@Table(name = "ARTICLE")
public class Article implements java.io.Serializable {

	private String articleId;
	private String articleType;
	private String articleTitle;
	private String articleDesc;
	private String keyWord;
	private String articleContent;
	private String createUserId;
	private Date createDate;
	private String updateUserId;
	private Date updateDate;
	private Long dispOrder;

	public Article() {
	}

	public Article(String articleId) {
		this.articleId = articleId;
	}

	public Article(String articleId, String articleType, String articleTitle,
			String articleDesc, String keyWord, String articleContent,
			String createUserId, Date createDate, String updateUserId,
			Date updateDate, Long dispOrder) {
		this.articleId = articleId;
		this.articleType = articleType;
		this.articleTitle = articleTitle;
		this.articleDesc = articleDesc;
		this.keyWord = keyWord;
		this.articleContent = articleContent;
		this.createUserId = createUserId;
		this.createDate = createDate;
		this.updateUserId = updateUserId;
		this.updateDate = updateDate;
		this.dispOrder = dispOrder;
	}

	@Id
	@Column(name = "ARTICLE_ID", unique = true, nullable = false, length = 32)
	@GenericGenerator(name="generator",strategy="uuid.hex")
    @GeneratedValue(generator="generator")
	public String getArticleId() {
		return this.articleId;
	}

	public void setArticleId(String articleId) {
		this.articleId = articleId;
	}

	@Column(name = "ARTICLE_TYPE")
	public String getArticleType() {
		return this.articleType;
	}

	public void setArticleType(String articleType) {
		this.articleType = articleType;
	}

	@Column(name = "ARTICLE_TITLE", length = 200)
	public String getArticleTitle() {
		return this.articleTitle;
	}

	public void setArticleTitle(String articleTitle) {
		this.articleTitle = articleTitle;
	}

	@Column(name = "ARTICLE_DESC", length = 1000)
	public String getArticleDesc() {
		return this.articleDesc;
	}

	public void setArticleDesc(String articleDesc) {
		this.articleDesc = articleDesc;
	}

	@Column(name = "KEY_WORD", length = 100)
	public String getKeyWord() {
		return this.keyWord;
	}

	public void setKeyWord(String keyWord) {
		this.keyWord = keyWord;
	}

	@Column(name = "ARTICLE_CONTENT")
	public String getArticleContent() {
		return this.articleContent;
	}

	public void setArticleContent(String articleContent) {
		this.articleContent = articleContent;
	}

	@Column(name = "CREATE_USER_ID", length = 32)
	public String getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(String createUserId) {
		this.createUserId = createUserId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "UPDATE_USER_ID", length = 32)
	public String getUpdateUserId() {
		return this.updateUserId;
	}

	public void setUpdateUserId(String updateUserId) {
		this.updateUserId = updateUserId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATE_DATE")
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "DISP_ORDER", precision = 10, scale = 0)
	public Long getDispOrder() {
		return this.dispOrder;
	}

	public void setDispOrder(Long dispOrder) {
		this.dispOrder = dispOrder;
	}

}
