package com.imark.system.model;
// Generated 2016-3-8 21:27:40 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysRole generated by hbm2java
 */
@Entity
@Table(name="SYS_ROLE")
public class SysRole  implements java.io.Serializable {


     private String id;
     private String roleName;
     private String roleType;
     private String isUse;
     private String memo;
     private Long orderNo;
     private String updateUser;
     private Date updateDate;

    public SysRole() {
    }

	
    public SysRole(String id, String roleName) {
        this.id = id;
        this.roleName = roleName;
    }
    public SysRole(String id, String roleName, String roleType, String isUse, String memo, Long orderNo, String updateUser, Date updateDate) {
       this.id = id;
       this.roleName = roleName;
       this.roleType = roleType;
       this.isUse = isUse;
       this.memo = memo;
       this.orderNo = orderNo;
       this.updateUser = updateUser;
       this.updateDate = updateDate;
    }
   
     @Id 
    
    @Column(name="ID", unique=true, nullable=false, length=36)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    @Column(name="ROLE_NAME", nullable=false, length=50)
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
    
    @Column(name="ROLE_TYPE", length=1)
    public String getRoleType() {
        return this.roleType;
    }
    
    public void setRoleType(String roleType) {
        this.roleType = roleType;
    }
    
    @Column(name="IS_USE", length=1)
    public String getIsUse() {
        return this.isUse;
    }
    
    public void setIsUse(String isUse) {
        this.isUse = isUse;
    }
    
    @Column(name="MEMO", length=500)
    public String getMemo() {
        return this.memo;
    }
    
    public void setMemo(String memo) {
        this.memo = memo;
    }
    
    @Column(name="ORDER_NO", precision=10, scale=0)
    public Long getOrderNo() {
        return this.orderNo;
    }
    
    public void setOrderNo(Long orderNo) {
        this.orderNo = orderNo;
    }
    
    @Column(name="UPDATE_USER", length=36)
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="UPDATE_DATE")
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }




}


